### ISSUE TITLE
Architecture Proposal

### ISSUE THREAD

**Issue by quevangel** [daque-dev/tasks.sh#1]
* Program Files
  * $HOME/.config/tasks/init.sh : Will be sourced on shell startup.
  * $HOME/.config/tasks/aliases.sh: Will contain the global aliases.
  * $HOME/.config/tasks/taskfileperdir.sh: Will contain the directory -> task file association.

* Operation
  * On shell startup: The init.sh file is sourced.  The aliases and directory->taskfile association is loaded into memory.
  * On task file creation inside the current directory:  The tasks names, tasks commands, tasks aliases and task file name are queried from the user.  The task file is created as a shell script that receives a task name **or** task alias and executes the associated command.  The given aliases are created if they don't exist already and consequently written into the aliases.sh file.  The directory and taskfile is inserted into the directory->taskfile map and consequently written on the taskfileperdir.sh file.
  * On alias use: every alias "x" will be translated into the following actions: get the task file from the current working directory and the directory->taskfile associative array and if it doesn't exist give a corresponding error message, execute the taskfile with "x" as the only argument.

**Comment by quevangel** [comment]
Example: 
  In the directory $HOME/project/ I have an associated task file named myprettytaskfile.sh
  I execute the command "b": "b" will do the following actions:
    1. Get the task file name from the associative array in taskfileperdir.sh given that I am in the directory $HOME/project this will result in "myprettytaskfile.sh".
    2. Execute "myprettytaskfile.sh b"
  Inside myprettytaskfile.sh "b" will be considered in the same case as "build" so it would functionally be the same as if I have manually executed "myprettytaskfile.sh build".

**Comment by davidomarf** [comment]
I have some questions:

- What is in `init.sh`?
- From my understanding, it looks like the alias `b` will be aliased to '. ./taskfile b', but this would require that the given './taskfile' to contain 'b' as possible argument, which, even if defined by the user, would make it harder to understand. I'd prefer to associate an alias (`b`) with a task-name (`build`), so the `./taskfile` is more explicit about what each task does.

**Comment by quevangel** [comment]
1. What is init.sh?  init.sh will just source aliases.sh and taskfileperdir.sh
2. Strictly, b would be aliased to "task_file=task_file_per_dir[$(pwd)];  $task_file b;" or something like that.  Which would eventually be "./taskfile b", yes.   To address this issue we could add another associative array which, given the current directory **and** the given alias would give the corresponding task name, in this case, this would map ($HOME/project, b) => build.

**Comment by quevangel** [comment]
All of this is so that "b" can be alised to different things given the current directory.  That is, that if I am in directory A this translates into "build" and if I am in directory B this translates into "backup".

**Comment by davidomarf** [comment]
So, trying to write it from my understanding:

Assuming I have the following directory structure:

```
.
└── project/
    └── project-tasks.sh
```

running

```sh
b
```

Will trigger these actions:

1. Look for the corresponding file for the directory I'm currently in  (`project`*).
2. Given that `./project/`* exists in `taskfileperdir.sh`*, and it's associated with `./project-tasks.sh`*, it'll continue.
3. Run `./project-tasks.sh b`*, which is mapped to whatever your local project custom `b` command is.
4. **profit**

\* paths are not correct, only the name of the files should be understood.

---

Could the script detect, and manage subdirectories so if there's a directory inside `taskfileperdir.sh` that is ancestor of the current directory, it runs that command?

The last question would be a nice feat to have. But in any way, I like this architecture and would like to proceed with it.

**Comment by quevangel** [comment]
> Could the script detect, and manage subdirectories so if there's a directory inside `taskfileperdir.sh` that is ancestor of the current directory, it runs that command?
> 
> The last question would be a nice feat to have. But in any way, I like this architecture and would like to proceed with it.

Yes, it could.  It would just be a matter of decomposing the current directory into it's components and try each each superdirectory giving priority to lower directories, that is, if the current working directory is /A/B/C try the directories /A/B/C then /A/B/ then /A/ and stop at the first succesful match.

**Comment by davidomarf** [comment]
Ok, I think we should just create some dummy files so we have a reference to it. 
I'll upload a sample in short, i'll tag you so you can correct them or extend them.
